spring.application.name=detalle-ms
server.port=8083
spring.datasource.url=jdbc:h2:mem:detalle_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.open-in-view=false
